import { SimpleNavbarWithHoverEffects } from "@/components/ui/layout/resizeable-navbar";
import { CenteredWithLogo } from "@/components/ui/layout/footer";
import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased`}
      >
        <SimpleNavbarWithHoverEffects />
        {children}
        <CenteredWithLogo />
      </body>
    </html>
  );
}
